name: Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Hugo and Tailwindcss
        run: ./init.sh

      - name: Build
        run: ./build.sh

      - name: Disable Jekyll
        run: touch hugo/public/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: hugo/public
          git-config-name: Andrey Akinshin
          git-config-email: andrey.akinshin@gmail.com
          clean: true
